name: Build Docker Image
on:
  push:
    branches:
      - develop
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dependency Docker Image
        uses: actions/checkout@v2

      - name: Check changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Build dependency docker image if needed
        if: contains(steps.files.outputs.all, 'package.json')
        run: |
          echo "package.json has been changed"
          docker login ${{ secrets.DOCKER_REGISTRY_HOST }} -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_SECRET }}
          npm run docker:publish:dep:dev
      - name: Build docker image
        run: |
          ${{ secrets.DOCKER_LOGIN }}
#          docker login ${{ secrets.DOCKER_REGISTRY_HOST }} -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_SECRET }}
          npm run docker:publish:dev
